import { createHash } from 'node:crypto';

export interface TokenSpec {
    name: string;
    symbol: string;
    decimals?: number;
    initialSupply: string;
    owner: string;
    mintable?: boolean;
    burnable?: boolean;
    pausable?: boolean;
}

export interface NormalizedTokenSpec extends Required<TokenSpec> { initialSupplyUnits: string; }

export interface ForgeResult {
    contractName: string;
    fileName: string;
    source: string;
    sourceHash: string;
    spec: NormalizedTokenSpec;
    compilerInput: { fileName: string; contractName: string; source: string; optimizer: { enabled: boolean; runs: number } };
}

function parseUnits(value: string, decimals: number): bigint {
    if (!/^(0|[1-9]\d*)(\.\d+)?$/.test(value)) throw new Error('initialSupply must be a non-negative decimal string');
    const [whole, fraction = ''] = value.split('.');
    if (fraction.length > decimals) throw new Error(`initialSupply has more than ${decimals} decimal places`);
    return BigInt(whole) * (10n ** BigInt(decimals)) + BigInt((fraction + '0'.repeat(decimals)).slice(0, decimals) || '0');
}

export function normalizeSpec(input: TokenSpec): NormalizedTokenSpec {
    const name = input.name?.trim();
    const symbol = input.symbol?.trim().toUpperCase();
    const decimals = input.decimals ?? 18;
    if (!name || name.length > 64) throw new Error('name must contain 1 to 64 characters');
    if (!symbol || !/^[A-Z][A-Z0-9]{0,10}$/.test(symbol)) throw new Error('symbol must contain 1 to 11 uppercase letters or digits');
    if (!Number.isInteger(decimals) || decimals < 0 || decimals > 36) throw new Error('decimals must be an integer from 0 to 36');
    if (!/^0x[0-9a-fA-F]{40}$/.test(input.owner || '')) throw new Error('owner must be a 20-byte Ethereum address');
    const units = parseUnits(String(input.initialSupply), decimals);
    if (units > (2n ** 256n) - 1n) throw new Error('initialSupply exceeds uint256');
    return { name, symbol, decimals, initialSupply: String(input.initialSupply), initialSupplyUnits: units.toString(), owner: input.owner, mintable: Boolean(input.mintable), burnable: Boolean(input.burnable), pausable: Boolean(input.pausable) };
}

export function contractIdentifier(name: string, symbol: string): string {
    const words = `${name} ${symbol}`.match(/[A-Za-z0-9]+/g) || ['Token'];
    const identifier = words.map(word => word[0].toUpperCase() + word.slice(1)).join('').replace(/^[0-9]+/, '');
    return `${identifier || 'Token'}Token`;
}

function buildSource(spec: NormalizedTokenSpec, contractName: string): string {
    const pauseState = spec.pausable ? '\n    bool public paused;\n    event Paused(bool status);' : '';
    const pauseGuard = spec.pausable ? ' require(!paused, "Token paused");' : '';
    const mint = spec.mintable ? `
    function mint(address to, uint256 amount) external onlyOwner {
        require(to != address(0), "Zero recipient");
        totalSupply += amount;
        balanceOf[to] += amount;
        emit Transfer(address(0), to, amount);
    }
` : '';
    const burn = spec.burnable ? `
    function burn(uint256 amount) external {
        require(balanceOf[msg.sender] >= amount, "Insufficient balance");
        balanceOf[msg.sender] -= amount;
        totalSupply -= amount;
        emit Transfer(msg.sender, address(0), amount);
    }
` : '';
    const pause = spec.pausable ? `
    function setPaused(bool status) external onlyOwner {
        paused = status;
        emit Paused(status);
    }
` : '';
    return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @notice ERC-20 token generated by TokenForgeMax.
contract ${contractName} {
    string public constant name = ${JSON.stringify(spec.name)};
    string public constant symbol = ${JSON.stringify(spec.symbol)};
    uint8 public constant decimals = ${spec.decimals};
    uint256 public totalSupply;
    address public owner;${pauseState}

    mapping(address => uint256) public balanceOf;
    mapping(address => mapping(address => uint256)) public allowance;

    event Transfer(address indexed from, address indexed to, uint256 value);
    event Approval(address indexed owner, address indexed spender, uint256 value);
    event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);

    modifier onlyOwner() { require(msg.sender == owner, "Not owner"); _; }

    constructor(address initialOwner) {
        require(initialOwner != address(0), "Zero owner");
        owner = initialOwner;
        totalSupply = ${spec.initialSupplyUnits};
        balanceOf[initialOwner] = totalSupply;
        emit Transfer(address(0), initialOwner, totalSupply);
        emit OwnershipTransferred(address(0), initialOwner);
    }

    function transfer(address to, uint256 amount) external returns (bool) {
        _transfer(msg.sender, to, amount);
        return true;
    }

    function approve(address spender, uint256 amount) external returns (bool) {
        allowance[msg.sender][spender] = amount;
        emit Approval(msg.sender, spender, amount);
        return true;
    }

    function transferFrom(address from, address to, uint256 amount) external returns (bool) {
        uint256 allowed = allowance[from][msg.sender];
        require(allowed >= amount, "Insufficient allowance");
        if (allowed != type(uint256).max) allowance[from][msg.sender] = allowed - amount;
        _transfer(from, to, amount);
        return true;
    }

    function transferOwnership(address newOwner) external onlyOwner {
        require(newOwner != address(0), "Zero owner");
        emit OwnershipTransferred(owner, newOwner);
        owner = newOwner;
    }
${mint}${burn}${pause}
    function _transfer(address from, address to, uint256 amount) internal {${pauseGuard}
        require(to != address(0), "Zero recipient");
        require(balanceOf[from] >= amount, "Insufficient balance");
        balanceOf[from] -= amount;
        balanceOf[to] += amount;
        emit Transfer(from, to, amount);
    }
}
`;
}

export class TokenForgeMax {
    forge(input: TokenSpec): ForgeResult {
        const spec = normalizeSpec(input);
        const contractName = contractIdentifier(spec.name, spec.symbol);
        const fileName = `${contractName}.sol`;
        const source = buildSource(spec, contractName);
        return { contractName, fileName, source, sourceHash: `sha256:${createHash('sha256').update(source).digest('hex')}`, spec, compilerInput: { fileName, contractName, source, optimizer: { enabled: true, runs: 200 } } };
    }

    async compile(result: ForgeResult, compilerUrl: string, fetchImpl: typeof fetch = fetch): Promise<unknown> {
        const url = new URL('/api/compile', compilerUrl);
        if (!['http:', 'https:'].includes(url.protocol)) throw new Error('compilerUrl must use HTTP or HTTPS');
        const response = await fetchImpl(url, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(result.compilerInput) });
        const payload = await response.json() as { error?: { message?: string } };
        if (!response.ok) throw new Error(payload.error?.message || `Compiler API returned HTTP ${response.status}`);
        return payload;
    }
}
